version: '3.8'
services:
  expense-db:
    image: mongo:latest
    container_name: expense-mongo
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password